# Generated by Django 4.1 on 2023-10-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('brend', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=256)),
                ('year_of_pruduction', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('count', models.IntegerField(default=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
